[package]
name = "fix-stacks"
version = "0.1.0"
authors = ["Nicholas Nethercote <nnethercote@mozilla.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
fxhash = "0.2.1"
goblin = "0.1.2"
regex = "1.0"
serde_json = "1.0"

# FIXME(https://github.com/mozilla/fix-stacks/issues/2): at the time of
# writing, 6.1.4 is the latest version of `symbolic` on crates.io, but this dev
# version of 7.0.0 fixes some API botches (`ObjectDebugSession::functions()`
# being private). Once 7.0.0 is released, we can switch to it.
#
# FIXME(https://github.com/mozilla/fix-stacks/issues/11): if/when my
# symbolic-debuginfo changes land
# (https://github.com/getsentry/symbolic/pull/173), change these to point again
# to the `getsentry` repo.
#
symbolic-common = { git = "https://github.com/nnethercote/symbolic/", rev = "7d4ca78958aab62104a9fc18bb17cdba616d7a63" }
symbolic-debuginfo = { git = "https://github.com/nnethercote/symbolic/", rev = "7d4ca78958aab62104a9fc18bb17cdba616d7a63" }
symbolic-demangle = { git = "https://github.com/nnethercote/symbolic/", rev = "7d4ca78958aab62104a9fc18bb17cdba616d7a63" }
